[package]
name = "actix_admin"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.1"
actix-session = { version = "0.7.1", features = [] }
actix-multipart = "0.4.0"
futures-util = "0.3.21"
chrono = "0.4.20"
tera = "1.16.0"
async-trait = "0.1.53"
lazy_static = "1.4.0"
serde = "1.0.136"
serde_derive = "1.0.136"
sea-orm = { version = "^0.9.1", features = [], default-features = false }

actix_admin_macros = { path = "actix_admin_macros" }