[package]
name = "actix-web-sample-app"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.12"
actix-rt = "2.5.0"
actix-session = "0.5.0-beta.4"

oauth2 = "4.1"
base64 = "0.13.0"

rand = "0.8.4"
url = "2.2.2"
http = "0.2.5"

futures = "0.3.18"
serde = "1.0.130"
serde_json = "1.0.71"
serde_derive = "1.0.130"