[package]
name = "actix_admin"
description = "An admin interface for actix-web"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"
exclude = [
    "example/*",
    "actix_admin_macros/*",
    "tests/*",
    "README.md",
    "static/*",
    "azure_auth/*",
]

[dependencies]
actix-web = "4.0.1"
actix-session = { version = "0.7.1", features = [] }
actix-multipart = "0.4.0"
futures-util = "0.3.21"
chrono = "0.4.20"
tera = "1.16.0"
async-trait = "0.1.53"
lazy_static = "1.4.0"
itertools = "0.10.3"
serde = "1.0.136"
serde_derive = "1.0.136"
sea-orm = { version = "^0.9.1", features = [], default-features = false }
actix_admin_macros = { version = "0.1.0", path = "actix_admin_macros" }

[dev-dependencies]
sea-orm = { version = "^0.9.1", features = [ "sqlx-sqlite", "runtime-actix-native-tls", "macros" ], default-features = true }